version: '3.8'
services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspaces/java1:cached      
      - ./webapps:/usr/local/tomcat/webapps:cached
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: sleep infinity
    working_dir: /workspaces/java1