/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SubtractionFun */

#ifndef _Included_SubtractionFun
#define _Included_SubtractionFun
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SubtractionFun
 * Method:    subtractValues
 * Signature: (DD)I
 */
JNIEXPORT jint JNICALL Java_SubtractionFun_subtractValues
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
