/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SpaceTravel */

#ifndef _Included_SpaceTravel
#define _Included_SpaceTravel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SpaceTravel
 * Method:    measureDistance
 * Signature: (DD)I
 */
JNIEXPORT jint JNICALL Java_SpaceTravel_measureDistance
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
